# -*- coding: utf-8 -*-
"""Descriptive Analytics .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYn8UwcLdjTD4P4iOvDrnuZmW-E0_x9s
"""

!pip install pandas numpy matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Sample student marks dataset

data = {
    'Student': ['A','B','C','D','E'],
    'Marks': [75, 80, 85, 90, 95]
}

# Create DataFrame

df = pd.DataFrame(data)

print(df)

# Mean

mean_value = df['Marks'].mean()

# Median

median_value = df['Marks'].median()

# Mode

mode_value = df['Marks'].mode()[0]

# Standard Deviation

std_value = df['Marks'].std()

# Display results

print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)
print("Standard Deviation:", std_value)

print(df.describe())

plt.figure(figsize=(7,5))

plt.bar(df['Student'],
        df['Marks'],
        color='blue')

plt.title("Student Marks Analysis")
plt.xlabel("Students")
plt.ylabel("Marks")

plt.show()

plt.figure(figsize=(7,5))

plt.hist(df['Marks'],
         bins=5,
         color='green')

plt.title("Marks Distribution")
plt.xlabel("Marks")
plt.ylabel("Frequency")

plt.show()

plt.figure(figsize=(6,4))

sns.boxplot(y=df['Marks'])

plt.title("Box Plot Analysis")

plt.show()

print("Descriptive Analytics Completed Successfully!")